name: Login tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for the tests (staging/production)'
        required: true
        default: 'staging'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://autotestreadtheory.testops.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 1
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - run: allurectl watch -- ./gradlew -x test loginTest -Denvironment=$ENVIRONMENT
        env:
          ALLURE_RESULTS: app/build/allure-results
